definitions:
  schemas.InputJWTClaims:
    properties:
      subject:
        type: string
    required:
    - subject
    type: object
  schemas.JWKResponse:
    properties:
      private_b64:
        type: string
      public_b64:
        type: string
    type: object
  schemas.PublicJWKResponse:
    properties:
      keys:
        items:
          properties:
            alg:
              type: string
            e:
              type: string
            kid:
              type: string
            kty:
              type: string
            "n":
              type: string
            use:
              type: string
          type: object
        type: array
    type: object
info:
  contact: {}
paths:
  /jwk/generate:
    get:
      consumes:
      - application/json
      description: Randomly generates a jwk pair (public and private)
      operationId: generate-jwk
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.JWKResponse'
      summary: Generates a new Jwk pair
  /jwk/public:
    get:
      description: Gets the public JWK
      operationId: get-public-jwk
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PublicJWKResponse'
      summary: Gets the current public JWK
  /jwt/generate:
    post:
      consumes:
      - application/json
      description: Randomly generates a json web token baes on a subject
      operationId: generate-jwt
      parameters:
      - description: Body for subject
        in: body
        name: b
        required: true
        schema:
          $ref: '#/definitions/schemas.InputJWTClaims'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Generates a new JSON Web Token
swagger: "2.0"
