apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
spec:
  profile: default
  hub: gcr.io/istio-release
  tag: latest
  revision: 1-8-0
  components:
    ingressGateways:
      - name: istio-ingress
        namespace: default
        enabled: true
        k8s: 
          service: ClusterIP
          overlays:
            - kind: Deployment
              name: istio-ingress-deployment
              patches:
              - path: metadata.labels.app
                value: istio-ingress-deployment
              - path: spec.selector.matchLabels.app
                value: istio-ingress-deployment
              - path: spec.template.metadata.labels.app
                value: istio-ingress-deployment

            - kind: Service
              name: istio-ingress-service
              patches:
              - path: spec.selector.app
                value: istio-ingress-deployment