definitions:
  controllers.ErrorResponse:
    properties:
      failedField:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  dto.JWK:
    properties:
      alg:
        example: ES256
        type: string
      crv:
        example: P-256
        type: string
      kid:
        example: a2V5SWRGb3JUZXN0aW5nCg==
        type: string
      kty:
        example: EC
        type: string
      use:
        example: sig
        type: string
      x:
        example: eEVsaXB0aWNDb29yZGluYXRlRm9ydGVzdGluZwo=
        type: string
      "y":
        example: eUVsaXB0aWNDb29yZGluYXRlRm9ydGVzdGluZwo=
        type: string
    type: object
  dto.JwkResponse:
    properties:
      private_b64:
        example: eyJ1c2UiOiJzaWciLCJrdHkiOiJFQyIsImtpZCI6IlZMRmZNck9VbVpOM1lISThrc0xkeFktUVJoX2lFd2dscVh4N2I1TUVBeHM9IiwiY3J2IjoiUC0yNTYiLCJhbGciOiJFUzI1NiIsIngiOiJiakR5c3VfZ09McXZPSFF4cnJwa3YxVDhOSFR6aUVUU0NySHpWM3luZ0djIiwieSI6IlV5bTZEWlRObHBIaDZvRUl4YkRDb0Jya05Lb01DU3ZQOW9GOVJtNFpVdjgiLCJkIjoiVkJDYkpkang1ajFxWUg4ek1JYUNJOVpXRWVac2JlUWxIc1pZQzRJMnRnNCJ9
        type: string
      public_b64:
        example: eyJ1c2UiOiJzaWciLCJrdHkiOiJFQyIsImtpZCI6IlZMRmZNck9VbVpOM1lISThrc0xkeFktUVJoX2lFd2dscVh4N2I1TUVBeHM9IiwiY3J2IjoiUC0yNTYiLCJhbGciOiJFUzI1NiIsIngiOiJiakR5c3VfZ09McXZPSFF4cnJwa3YxVDhOSFR6aUVUU0NySHpWM3luZ0djIiwieSI6IlV5bTZEWlRObHBIaDZvRUl4YkRDb0Jya05Lb01DU3ZQOW9GOVJtNFpVdjgifQ==
        type: string
    type: object
  dto.JwtClaimsInput:
    properties:
      fqn:
        example: Fully Qualified Name of the Subject
        maxLength: 40
        minLength: 3
        type: string
      groups:
        example:
        - group 1
        - group 2
        items:
          type: string
        maxItems: 10
        minItems: 1
        type: array
      subject:
        example: Subject of the JWT
        maxLength: 32
        minLength: 3
        type: string
    required:
    - fqn
    - groups
    - subject
    type: object
  dto.JwtResponse:
    properties:
      id_token:
        example: eyJhbGciOiJFUzI1NiIsImtpZCI6IlN6Qy1Ta2VUMl9vYTFwZ3lzOXpGV2VmM3hKTXZTUmtpdlBqQkloeDQ4cEk9In0.eyJhdWQiOiJpbnRlcm5hbC1jZW5ldmFsLWVtcGxveWVlcyIsImV4cCI6MTY0OTk5MjQ1OSwiZ3JvdXBzIjpudWxsLCJpYXQiOjE2NDk5ODg4NTksImlzcyI6InBsYXRhZm9ybWEuY2VuZXZhbC5lZHUubXgiLCJzdWIiOiJzdHJpbmcifQ.GCz1NTtAZyQMXYj9--dVXOn1k-0nezqP4TkP_WtI3Be4r6SCiuExmMIc6Wlb-tE48oaLaxEylJCxVimK-BdOaw
        type: string
      refresh_token:
        example: eyJhbGciOiJFUzI1NiIsImtpZCI6IlN6Qy1Ta2VUMl9vYTFwZ3lzOXpGV2VmM3hKTXZTUmtpdlBqQkloeDQ4cEk9In0.eyJ1c2VyX2lkIjoic3RyaW5nIn0.5zL9n6ZMtmeTH4gEKKOiymPkIJYZdDy5Xq_S621PHcEQVjuYsKSYlmZBmIvRd6NfltBQbUR-VPzRmFwIgYKQvA
        type: string
    type: object
  dto.JwtValidResponse:
    properties:
      is_valid:
        example: false
        type: boolean
    type: object
  dto.ValidateJwtInput:
    properties:
      jwt:
        example: Jwt in base64 form
        minLength: 10
        type: string
    required:
    - jwt
    type: object
info:
  contact: {}
  description: Sample service for showcasing istio capabilities in edge JWT authentication
  title: JWT authentication API
  version: 0.0.1
paths:
  /jwk/generate:
    get:
      consumes:
      - application/json
      description: Randomly generates a jwk pair (public and private)
      operationId: generate-jwk
      produces:
      - application/json
      responses:
        "201":
          description: JWK pair successfully created
          schema:
            $ref: '#/definitions/dto.JwkResponse'
      summary: Generates a new Jwk pair
      tags:
      - jwk
  /jwk/public:
    get:
      consumes:
      - application/json
      description: Gets the public JWK Set in json format
      operationId: public-jwk
      produces:
      - application/json
      responses:
        "200":
          description: JWK public set, for more information refer to https://tools.ietf.org/id/draft-ietf-jose-json-web-key-00.html#:~:text=Abstract,a%20set%20of%20public%20keys.
          schema:
            items:
              $ref: '#/definitions/dto.JWK'
            type: array
      summary: Gets the public JWK Set
      tags:
      - jwk
  /jwt/generate:
    post:
      consumes:
      - application/json
      description: Randomly generates a jwt based on claims
      operationId: generate-jwt
      parameters:
      - description: claims body
        in: body
        name: claims
        required: true
        schema:
          $ref: '#/definitions/dto.JwtClaimsInput'
      produces:
      - application/json
      responses:
        "201":
          description: JWT pair successfully created
          schema:
            $ref: '#/definitions/dto.JwtResponse'
      summary: Generates a new JWT
      tags:
      - jwt
  /jwt/validate-id-token:
    post:
      consumes:
      - application/json
      description: Validates an Id token in the form of base64
      operationId: validate-id-token
      parameters:
      - description: JWT to validate
        in: body
        name: jwt
        required: true
        schema:
          $ref: '#/definitions/dto.ValidateJwtInput'
      produces:
      - application/json
      responses:
        "200":
          description: Returns wheter the JWT is valid or not
          schema:
            $ref: '#/definitions/dto.JwtValidResponse'
        "400":
          description: JWT has some error
          schema:
            items:
              $ref: '#/definitions/controllers.ErrorResponse'
            type: array
      summary: Validate a new Id token
      tags:
      - jwt
  /jwt/validate-refresh-token:
    post:
      consumes:
      - application/json
      description: Validates a refresh token in form of a base64 jwt
      operationId: validate-refresh-token
      parameters:
      - description: JWT to validate
        in: body
        name: jwt
        required: true
        schema:
          $ref: '#/definitions/dto.ValidateJwtInput'
      produces:
      - application/json
      responses:
        "200":
          description: Returns wheter the JWT is valid or not
          schema:
            $ref: '#/definitions/dto.JwtValidResponse'
        "400":
          description: JWT has some error
          schema:
            items:
              $ref: '#/definitions/controllers.ErrorResponse'
            type: array
      summary: Validate a refresh token
      tags:
      - jwt
swagger: "2.0"
